import type { DSASection } from '@/types/dsa';

export const basicRecursionSection: DSASection = {
  id: 'basic-recursion',
  slug: 'basic-recursion',
  title: 'Learn Basic Recursion',
  description: 'Build a solid foundation in recursion — the backbone of backtracking, trees, graphs, and dynamic programming.',
  icon: '🔁',
  color: 'from-cyan-500 to-blue-600',
  topics: [
    {
      id: 'recursion-intro',
      slug: 'recursion-intro',
      title: 'Understanding Recursion by Printing N Times',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Recursion Basics',
      introduction: `Recursion is the most important concept you will learn in DSA. Every hard DSA problem (trees, graphs, DP, backtracking) uses recursion at its core. The best way to build intuition is to start with the simplest possible recursive programs.`,
      theory: `**What is recursion?** A function calling itself with a smaller input until a base case is reached.\n\n**Two essential parts of every recursive function:**\n1. **Base case** — When to stop. Without this, you get infinite recursion (stack overflow).\n2. **Recursive case** — Calls itself with a simpler/smaller input.\n\n**The Call Stack:** Each function call creates a stack frame. In recursion, frames stack up until the base case is hit, then unwind in reverse.\n\n**Mental Model:** Think of recursion as a tree of function calls. Each node is a call, children are recursive calls, leaves are base cases.\n\n**How to think recursively:**\n- Assume the recursive call already solves the smaller problem.\n- Your job is just to use that result to solve the current problem.\n- Trust the recursion.`,
      problemStatement: 'Write a recursive function to print your name N times.',
      examples: [
        { input: 'N=3, name="Ghanshyam"', output: 'Ghanshyam\nGhanshyam\nGhanshyam' },
      ],
      approaches: [
        {
          name: 'Recursion with counter',
          intuition: 'Print the name once, then recurse with count-1. Stop when count reaches 0.',
          steps: ['Base case: if count == 0, return', 'Print name', 'Call recursively with count-1'],
          complexity: { time: 'O(N)', space: 'O(N) — call stack' },
          code: `void printName(int count, string name) {\n    if (count == 0) return;  // base case\n    cout << name << "\\n";   // print\n    printName(count - 1, name);  // recurse\n}`,
          dryRun: 'printName(3): prints "Ghanshyam", calls printName(2). printName(2): prints, calls printName(1). printName(1): prints, calls printName(0). printName(0): returns. Stack unwinds.',
        },
      ],
      hints: [
        'What is the smallest case? When n=0, do nothing (base case).',
        'What happens at each step? Print once, then solve for n-1.',
      ],
      solution: `void printName(int n, string name) {\n    if (n == 0) return;\n    cout << name << "\\n";\n    printName(n - 1, name);\n}`,
      keyTakeaways: [
        'Every recursive function MUST have a base case.',
        'The recursive call must move TOWARDS the base case (smaller input).',
        'Space complexity of recursion = O(depth of recursion tree) = call stack space.',
      ],
    },
    {
      id: 'print-1-to-n',
      slug: 'print-1-to-n',
      title: 'Print 1 to N using Recursion',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Recursion Basics',
      problemStatement: 'Without using loops, print numbers from 1 to N using recursion.',
      examples: [
        { input: 'N=5', output: '1 2 3 4 5' },
      ],
      approaches: [
        {
          name: 'Recursive (backtrack after base)',
          intuition: 'Call recursively first, print on the way BACK (backtracking). OR print first, then recurse.',
          steps: ['To print 1 to N: base case i > N. Print i. Call func(i+1).', 'OR: Call func(i-1), then print i (prints 1..N in order).'],
          complexity: { time: 'O(N)', space: 'O(N)' },
          code: `// Method 1: Print BEFORE recursive call\nvoid print1ToN(int i, int n) {\n    if (i > n) return;  // base case\n    cout << i << " ";  // print first\n    print1ToN(i + 1, n);  // then recurse\n}\n\n// Call: print1ToN(1, n)\n\n// Method 2: Recurse THEN print (understand call stack)\nvoid print1ToN_v2(int n) {\n    if (n == 0) return;\n    print1ToN_v2(n - 1);  // recurse first\n    cout << n << " ";     // print on RETURN (backtracking)\n}`,
          dryRun: 'Method 2, n=3: calls f(2)→f(1)→f(0)[return]. f(1) prints 1. f(2) prints 2. f(3) prints 3. Output: 1 2 3.',
        },
      ],
      hints: [
        'Try both approaches: print before recursion vs print after recursion.',
        'When you print AFTER the recursive call, you see the "backtracking" in action.',
        'Method 2 (recurse then print) prints in reverse N..1. But call first, then print gives N..1 reversed = 1..N.',
      ],
      solution: `void print1ToN(int i, int n) {\n    if (i > n) return;\n    cout << i << " ";\n    print1ToN(i + 1, n);\n}`,
      keyTakeaways: ['Printing BEFORE recursion = top-down (1..N). Printing AFTER recursion = bottom-up (prints after stack unwinds).'],
    },
    {
      id: 'print-n-to-1',
      slug: 'print-n-to-1',
      title: 'Print N to 1 using Recursion',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Recursion Basics',
      problemStatement: 'Without using loops, print numbers from N down to 1 using recursion.',
      examples: [{ input: 'N=5', output: '5 4 3 2 1' }],
      approaches: [
        {
          name: 'Recursive',
          intuition: 'Print current n, then recurse with n-1.',
          steps: ['Base case: n < 1, return', 'Print n', 'Recurse with n-1'],
          complexity: { time: 'O(N)', space: 'O(N)' },
          code: `void printNTo1(int n) {\n    if (n < 1) return;\n    cout << n << " ";\n    printNTo1(n - 1);\n}`,
        },
      ],
      hints: ['Print n first (before recursive call) to get N...1 order.'],
      solution: `void printNTo1(int n) {\n    if (n < 1) return;\n    cout << n << " ";\n    printNTo1(n - 1);\n}`,
      keyTakeaways: ['Print BEFORE recursion for descending. Print AFTER recursion for ascending.'],
    },
    {
      id: 'sum-of-n',
      slug: 'sum-of-n',
      title: 'Sum of First N Numbers using Recursion',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Recursion Basics',
      problemStatement: 'Find the sum of first N natural numbers using recursion.',
      examples: [
        { input: 'N=5', output: '15', explanation: '1+2+3+4+5=15' },
      ],
      approaches: [
        {
          name: 'Recursive',
          intuition: 'Sum(N) = N + Sum(N-1). Base: Sum(0) = 0.',
          steps: ['Base case: n == 0 return 0', 'Return n + sum(n-1)'],
          complexity: { time: 'O(N)', space: 'O(N)' },
          code: `int sum(int n) {\n    if (n == 0) return 0;  // base case\n    return n + sum(n - 1); // n + sum of (1 to n-1)\n}`,
          dryRun: 'sum(3) = 3 + sum(2) = 3 + (2 + sum(1)) = 3 + 2 + (1 + sum(0)) = 3+2+1+0 = 6.',
        },
      ],
      hints: ['Sum(n) = n + Sum(n-1). Trust the recursive call to return the correct sum.'],
      solution: `int sum(int n) {\n    if (n == 0) return 0;\n    return n + sum(n - 1);\n}`,
      keyTakeaways: ['Parameterized vs functional recursion: either pass result as parameter or return it.'],
    },
    {
      id: 'factorial-recursion',
      slug: 'factorial-recursion',
      title: 'Factorial using Recursion',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Recursion Basics',
      problemStatement: 'Compute N! (factorial) recursively. N! = N × (N-1) × ... × 1. 0! = 1.',
      examples: [
        { input: 'N=5', output: '120', explanation: '5×4×3×2×1=120' },
        { input: 'N=0', output: '1', explanation: '0! = 1 by definition' },
      ],
      approaches: [
        {
          name: 'Recursive',
          intuition: 'N! = N × (N-1)!. Base case: 0! = 1.',
          steps: ['Base case: n == 0 return 1', 'Return n * factorial(n-1)'],
          complexity: { time: 'O(N)', space: 'O(N)' },
          code: `long long factorial(int n) {\n    if (n == 0) return 1;\n    return (long long)n * factorial(n - 1);\n}`,
          dryRun: 'fact(4) = 4 × fact(3) = 4 × 3 × fact(2) = 4 × 3 × 2 × fact(1) = 4 × 3 × 2 × 1 × fact(0) = 4×3×2×1×1 = 24.',
        },
      ],
      hints: ['N! = N × (N-1)!. Base case: 0! = 1.', 'Use long long to avoid overflow for large N.'],
      solution: `long long factorial(int n) {\n    if (n == 0) return 1;\n    return (long long)n * factorial(n - 1);\n}`,
      keyTakeaways: ['Factorial is the canonical recursion example. Base case: 0!=1. Recursive: n!=n*(n-1)!'],
    },
    {
      id: 'reverse-array-recursion',
      slug: 'reverse-array-recursion',
      title: 'Reverse an Array using Recursion',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Recursion with Pointers',
      conceptsRequired: ['Two pointer', 'Pass by reference'],
      problemStatement: 'Reverse an array in-place using recursion.',
      examples: [
        { input: '[1,2,3,4,5]', output: '[5,4,3,2,1]' },
      ],
      approaches: [
        {
          name: 'Two pointer recursive',
          intuition: 'Swap first and last elements, then recurse on the inner portion.',
          steps: ['Base case: left >= right, return (0 or 1 element, already reversed)', 'Swap arr[left] and arr[right]', 'Recurse: reverse(arr, left+1, right-1)'],
          complexity: { time: 'O(N)', space: 'O(N/2) = O(N)' },
          code: `void reverse(vector<int>& arr, int left, int right) {\n    if (left >= right) return;  // base case\n    swap(arr[left], arr[right]); // swap extremes\n    reverse(arr, left + 1, right - 1); // recurse inward\n}`,
          dryRun: '[1,2,3,4,5]: swap(1,5)→[5,2,3,4,1], reverse([2,3,4]). swap(2,4)→[5,4,3,2,1], reverse([3]). Base case.',
        },
      ],
      hints: [
        'Swap the outermost elements, then solve the inner array.',
        'Base case: when left >= right (0 or 1 element remaining).',
      ],
      solution: `void reverse(vector<int>& arr, int l, int r) {\n    if (l >= r) return;\n    swap(arr[l], arr[r]);\n    reverse(arr, l + 1, r - 1);\n}`,
      keyTakeaways: ['The two-pointer pattern combined with recursion is used in quicksort and many other algorithms.'],
    },
    {
      id: 'palindrome-string-recursion',
      slug: 'palindrome-string-recursion',
      title: 'Check if String is Palindrome using Recursion',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Recursion with Pointers',
      problemStatement: 'Given a string, check if it is a palindrome using recursion (without loops).',
      examples: [
        { input: '"racecar"', output: 'true' },
        { input: '"hello"', output: 'false' },
      ],
      approaches: [
        {
          name: 'Two pointer recursive',
          intuition: 'A string is a palindrome if the first and last characters match AND the inner string is also a palindrome.',
          steps: ['Base case: left >= right (0 or 1 chars) → true', 'If s[left] != s[right] → false', 'Return isPalindrome(s, left+1, right-1)'],
          complexity: { time: 'O(N)', space: 'O(N)' },
          code: `bool isPalindrome(string& s, int left, int right) {\n    if (left >= right) return true; // base: done\n    if (s[left] != s[right]) return false;\n    return isPalindrome(s, left + 1, right - 1);\n}`,
        },
      ],
      hints: [
        'A palindrome has matching first and last characters.',
        'After verifying the first and last, check if the inner string is also a palindrome.',
      ],
      solution: `bool isPalindrome(string& s, int l, int r) {\n    if (l >= r) return true;\n    if (s[l] != s[r]) return false;\n    return isPalindrome(s, l + 1, r - 1);\n}`,
      keyTakeaways: ['Recursive palindrome check = verify outer chars + check inner substring.'],
    },
    {
      id: 'fibonacci-recursion',
      slug: 'fibonacci-recursion',
      title: 'Fibonacci Number',
      type: 'problem',
      difficulty: 'easy',
      pattern: 'Recursion / Dynamic Programming',
      conceptsRequired: ['Recursion', 'Memoization'],
      problemStatement: 'Compute the Nth Fibonacci number. F(0)=0, F(1)=1, F(n)=F(n-1)+F(n-2).',
      examples: [
        { input: 'N=7', output: '13', explanation: '0,1,1,2,3,5,8,13 — 7th (0-indexed) is 13.' },
        { input: 'N=10', output: '55' },
      ],
      theory: `**Naive recursion is exponential O(2^N).** Each call branches into 2, creating a binary tree of calls.\n\n**Memoization** fixes this: cache results to avoid recomputing. O(N) time, O(N) space.\n\n**This problem is the gateway to Dynamic Programming.** Understand WHY naive recursion is slow before learning memoization.`,
      approaches: [
        {
          name: 'Naive Recursion — O(2^N)',
          intuition: 'Direct translation of the definition.',
          steps: ['Base: f(0)=0, f(1)=1', 'Return f(n-1) + f(n-2)'],
          complexity: { time: 'O(2^N) — exponential!', space: 'O(N)' },
          code: `int fib(int n) {\n    if (n <= 1) return n;\n    return fib(n - 1) + fib(n - 2); // lots of recomputation\n}`,
          dryRun: 'fib(5) calls fib(4) and fib(3). fib(4) calls fib(3) and fib(2). fib(3) is computed TWICE — wasteful!',
        },
        {
          name: 'Memoization — O(N)',
          intuition: 'Cache results. If already computed, return from cache.',
          steps: ['Create a memo array initialized to -1', 'Before computing, check if memo[n] is set', 'Store result before returning'],
          complexity: { time: 'O(N)', space: 'O(N)' },
          code: `int fib(int n, vector<int>& memo) {\n    if (n <= 1) return n;\n    if (memo[n] != -1) return memo[n]; // cache hit\n    memo[n] = fib(n-1, memo) + fib(n-2, memo);\n    return memo[n];\n}\n// Call: vector<int> memo(n+1, -1); fib(n, memo);`,
        },
        {
          name: 'Iterative — O(N) time, O(1) space',
          intuition: 'Compute bottom-up. Only need previous two values.',
          steps: ['Use two variables prev and curr', 'At each step: new = prev + curr; prev = curr; curr = new'],
          complexity: { time: 'O(N)', space: 'O(1)' },
          code: `int fib(int n) {\n    if (n <= 1) return n;\n    int prev = 0, curr = 1;\n    for (int i = 2; i <= n; i++) {\n        int next = prev + curr;\n        prev = curr;\n        curr = next;\n    }\n    return curr;\n}`,
        },
      ],
      hints: [
        'F(n) = F(n-1) + F(n-2). Base: F(0)=0, F(1)=1.',
        'Naive recursion is O(2^N) — draw the call tree to see the repeated work.',
        'Memoization: cache results in an array to avoid recomputation.',
      ],
      solution: `// Memoized O(N)\nint fib(int n, vector<int>& memo) {\n    if (n <= 1) return n;\n    if (memo[n] != -1) return memo[n];\n    return memo[n] = fib(n-1, memo) + fib(n-2, memo);\n}`,
      leetcodeUrl: 'https://leetcode.com/problems/fibonacci-number/',
      keyTakeaways: [
        'Fibonacci is the gateway to DP. Understand why recursion is O(2^N) and memoization makes it O(N).',
        'Memoization = recursion + cache. Bottom-up DP = iterative + array.',
        'The O(1) space iterative solution uses rolling variables — fundamental DP optimization.',
      ],
    },
  ],
};
