import type { Track } from '@/types';

export const tracks: Track[] = [
  {
    id: 'javascript',
    name: 'JavaScript',
    description: 'Master JavaScript from fundamentals to advanced patterns. Closures, async/await, prototypes, and more.',
    icon: 'JS',
    available: true,
    color: 'from-yellow-500 to-amber-500',
    lessonCount: 30,
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    description: 'Level up with static typing, generics, decorators, and enterprise-grade TypeScript patterns.',
    icon: 'TS',
    available: false,
    color: 'from-blue-500 to-blue-600',
    lessonCount: 18,
  },
  {
    id: 'react',
    name: 'React',
    description: 'Build modern UIs with hooks, context, performance patterns, and React 19 features.',
    icon: 'RE',
    available: false,
    color: 'from-cyan-500 to-sky-500',
    lessonCount: 22,
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    description: 'Full-stack React with App Router, Server Components, streaming, and deployment.',
    icon: 'NX',
    available: false,
    color: 'from-gray-600 to-gray-700',
    lessonCount: 16,
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    description: 'Server-side JavaScript with Express, REST APIs, authentication, and databases.',
    icon: 'ND',
    available: false,
    color: 'from-green-600 to-emerald-600',
    lessonCount: 20,
  },
  {
    id: 'dsa',
    name: 'DSA',
    description: 'Data structures and algorithms: arrays, trees, graphs, sorting, dynamic programming.',
    icon: 'DS',
    available: false,
    color: 'from-violet-500 to-purple-600',
    lessonCount: 30,
  },
  {
    id: 'webdev',
    name: 'Web Development',
    description: 'HTML, CSS, Flexbox, Grid, responsive design, accessibility, and browser APIs from the ground up.',
    icon: 'WD',
    available: false,
    color: 'from-orange-500 to-rose-500',
    lessonCount: 25,
  },
  {
    id: 'system-design',
    name: 'System Design',
    description: 'Scalable architectures, load balancing, caching, databases, microservices, and real-world design patterns.',
    icon: 'SD',
    available: false,
    color: 'from-teal-500 to-cyan-600',
    lessonCount: 20,
  },
  {
    id: 'sql',
    name: 'SQL',
    description: 'Relational databases, joins, indexes, transactions, query optimization, and PostgreSQL.',
    icon: 'SQ',
    available: false,
    color: 'from-sky-500 to-blue-600',
    lessonCount: 18,
  },
  {
    id: 'github-actions',
    name: 'GitHub Actions',
    description: 'CI/CD pipelines, workflow syntax, secrets, matrix builds, caching, and deploying to cloud.',
    icon: 'GA',
    available: false,
    color: 'from-slate-500 to-gray-600',
    lessonCount: 12,
  },
  {
    id: 'docker',
    name: 'Docker',
    description: 'Containers, Dockerfile, docker-compose, volumes, networking, and Docker commands cheat sheet.',
    icon: 'DK',
    available: false,
    color: 'from-blue-400 to-blue-600',
    lessonCount: 14,
  },
  {
    id: 'ai',
    name: 'AI for Developers',
    description: 'Prompting, LLM APIs, embeddings, RAG, AI-powered apps, and integrating AI into your workflow.',
    icon: 'AI',
    available: false,
    color: 'from-purple-500 to-pink-500',
    lessonCount: 16,
  },
  {
    id: 'hld',
    name: 'High Level Design',
    description: 'Design scalable systems end-to-end: URL shortener, WhatsApp, Netflix, Uber, Twitter and more.',
    icon: 'HLD',
    available: false,
    color: 'from-emerald-500 to-teal-600',
    lessonCount: 15,
  },
  {
    id: 'lld',
    name: 'Low Level Design',
    description: 'OOP principles, design patterns, class diagrams, and LLD interviews: parking lot, elevator, chess.',
    icon: 'LLD',
    available: false,
    color: 'from-indigo-500 to-violet-600',
    lessonCount: 18,
  },
  {
    id: 'aptitude',
    name: 'Aptitude',
    description: 'Quantitative aptitude: number systems, percentages, time & work, profit & loss, permutations.',
    icon: 'APT',
    available: false,
    color: 'from-yellow-400 to-orange-500',
    lessonCount: 20,
  },
  {
    id: 'reasoning',
    name: 'Logical Reasoning',
    description: 'Verbal and non-verbal reasoning: series, analogies, coding-decoding, puzzles, syllogisms.',
    icon: 'LR',
    available: false,
    color: 'from-rose-500 to-pink-600',
    lessonCount: 20,
  },
  {
    id: 'cs-fundamentals',
    name: 'CS Fundamentals',
    description: 'OS concepts, process/threads, memory management, networking basics, DBMS — all in one place.',
    icon: 'CS',
    available: false,
    color: 'from-gray-500 to-slate-600',
    lessonCount: 24,
  },
  {
    id: 'behavioral',
    name: 'Behavioral Interviews',
    description: 'STAR method, common HR questions, leadership principles, conflict resolution, and self-intro.',
    icon: 'BEH',
    available: false,
    color: 'from-cyan-500 to-blue-500',
    lessonCount: 12,
  },
];
