import type { Track } from '@/types';

export const tracks: Track[] = [
  {
    id: 'javascript',
    name: 'JavaScript',
    description: 'Master JavaScript from fundamentals to advanced patterns. Closures, async/await, prototypes, and more.',
    icon: 'JS',
    available: true,
    color: 'from-yellow-500 to-amber-500',
    lessonCount: 30,
  },
  {
    id: 'typescript',
    name: 'TypeScript',
    description: 'Level up with static typing, generics, decorators, and enterprise-grade TypeScript patterns.',
    icon: 'TS',
    available: true,
    color: 'from-blue-500 to-blue-600',
    lessonCount: 18,
  },
  {
    id: 'react',
    name: 'React',
    description: 'Build modern UIs with hooks, context, performance patterns, and React 19 features.',
    icon: 'RE',
    available: false,
    color: 'from-cyan-500 to-sky-500',
    lessonCount: 22,
  },
  {
    id: 'nextjs',
    name: 'Next.js',
    description: 'Full-stack React with App Router, Server Components, streaming, and deployment.',
    icon: 'NX',
    available: true,
    color: 'from-gray-600 to-gray-700',
    lessonCount: 27,
  },
  {
    id: 'nodejs',
    name: 'Node.js',
    description: 'Node.js internals, Express, REST APIs, authentication, real-time, queues, caching, security, and production deployment.',
    icon: 'ND',
    available: true,
    color: 'from-green-600 to-emerald-600',
    lessonCount: 27,
  },
  {
    id: 'dsa',
    name: 'DSA',
    description: 'Data structures and algorithms: arrays, trees, graphs, sorting, dynamic programming — Striver A2Z Sheet.',
    icon: 'DS',
    available: true,
    color: 'from-violet-500 to-purple-600',
    lessonCount: 400,
  },
  {
    id: 'webdev',
    name: 'Web Development',
    description: 'HTML, CSS, Flexbox, Grid, responsive design, accessibility, and browser APIs from the ground up.',
    icon: 'WD',
    available: false,
    color: 'from-orange-500 to-rose-500',
    lessonCount: 25,
  },
  {
    id: 'system-design',
    name: 'System Design',
    description: 'HLD, LLD, distributed systems, scalability, caching, databases, microservices, design patterns, and real-world case studies — everything to design systems and crack interviews.',
    icon: 'SD',
    available: true,
    color: 'from-teal-500 to-cyan-600',
    lessonCount: 22,
  },
  {
    id: 'databases',
    name: 'Databases',
    description: 'SQL, NoSQL, PostgreSQL, MongoDB, Redis, ORMs, database design, indexing, transactions — everything a software engineer needs.',
    icon: 'DB',
    available: true,
    color: 'from-sky-500 to-blue-600',
    lessonCount: 21,
  },
  {
    id: 'aws',
    name: 'AWS Notes',
    description: 'AWS cloud services: EC2, S3, RDS, Lambda, IAM, VPC, CloudFront, and more — notes + interview prep.',
    icon: 'AW',
    available: true,
    color: 'from-orange-400 to-amber-500',
    lessonCount: 18,
  },
  {
    id: 'devops',
    name: 'DevOps',
    description: 'Linux, Docker, Dockerfiles, Docker Compose, GitHub Actions, CI/CD, cloud fundamentals, and Kubernetes — everything a developer needs to build, deploy, and ship.',
    icon: 'DO',
    available: true,
    color: 'from-orange-500 to-amber-600',
    lessonCount: 19,
  },
  {
    id: 'ai',
    name: 'AI for Developers',
    description: 'Prompting, LLM APIs, embeddings, RAG, AI-powered apps, and integrating AI into your workflow.',
    icon: 'AI',
    available: false,
    color: 'from-purple-500 to-pink-500',
    lessonCount: 16,
  },
  {
    id: 'aptitude',
    name: 'Aptitude',
    description: 'Quantitative aptitude: number systems, percentages, time & work, profit & loss, permutations.',
    icon: 'APT',
    available: false,
    color: 'from-yellow-400 to-orange-500',
    lessonCount: 20,
  },
  {
    id: 'reasoning',
    name: 'Logical Reasoning',
    description: 'Verbal and non-verbal reasoning: series, analogies, coding-decoding, puzzles, syllogisms.',
    icon: 'LR',
    available: false,
    color: 'from-rose-500 to-pink-600',
    lessonCount: 20,
  },
  {
    id: 'cs-fundamentals',
    name: 'CS Fundamentals',
    description: 'OS concepts, process/threads, memory management, networking basics, DBMS — all in one place.',
    icon: 'CS',
    available: false,
    color: 'from-gray-500 to-slate-600',
    lessonCount: 24,
  },
  {
    id: 'behavioral',
    name: 'Behavioral Interviews',
    description: 'STAR method, common HR questions, leadership principles, conflict resolution, and self-intro.',
    icon: 'BEH',
    available: false,
    color: 'from-cyan-500 to-blue-500',
    lessonCount: 12,
  },
];
